[build-system]
requires = ["setuptools>=59.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mazeenv"
version = "1.0.0"

dependencies = [
  "gymnasium>=0.29.1",
  "numpy>=1.26.2",
  "tqdm>=4.66.1",
  "pandas>=2.1.3",
  "seaborn>=0.13.0",
  "pygame>=2.5.2"
]